# config.yaml


# Data
precip_data_directory: "/reloclim/dkn/data/IMERG_most_final"
lifting_index_data_directory: "/reloclim/dkn/data/ERA5/lifting_index_old"
file_suffix: ".nc"
detection_output_path: "/reloclim/dkn/data/detection_tracking_output/detection"
tracking_output_dir: "/reloclim/dkn/data/detection_tracking_output/tracking"

grid_size_km: 11.0
precip_var_name: "precipitation"
liting_index_var_name: "LI"
lat_name: "lat"
lon_name: "lon"
data_source: "IMERG precipitation and ERA5 Lifting Index"

# Years and Months to process
# empty list uses all available data in the specified directory
years: [2001]
months: [5, 6, 7, 8, 9]

# Detection parametersS
min_size_threshold: 10
heavy_precip_threshold: 8.0
moderate_precip_threshold: 1.0
min_nr_plumes: 1
lifting_index_percentage_threshold: 0.2

# Tracking parameters
main_lifetime_thresh: 5
main_area_thresh: 2000
grid_cell_area_km2: 121
nmaxmerge: 5

# Other parameters
use_lifting_index: True
detection: True
use_multiprocessing: True
number_of_cores: 32
