# config.yaml


# Data
data_directory: "../tests/Test7/data/"
file_suffix: ".nc_test"
output_path: "../tests/Test7/"
tracking_output_dir: "../tests/Test7/"
grid_size_km: 11.0
var_name: "pr"
lat_name: "lat"
lon_name: "lon"
data_source: "Test data"

# Detection parametersS
min_size_threshold: 10
heavy_precip_threshold: 10.0
moderate_precip_threshold: 1.0
min_nr_plumes: 1


# Tracking parameters
main_lifetime_thresh: 6
main_area_thresh: 10000
grid_cell_area_km2: 1
nmaxmerge: 5

# Other parameters
detection: True
use_multiprocessing: True
number_of_cores: 4
