# config.yaml


# Data
precip_data_directory: "/data/reloclim/backup/MCS_database/raw_data/mcstracking/2017/08/"
lifting_index_data_directory: "/nas/home/dkn/Desktop/MoCCA/Derechos/LI_test/data/ERA5/hourly/201708/hourly"
file_suffix: ".nc"
detection_output_path: "/nas/home/dkn/Desktop/MoCCA/Derechos/LI_test/output/201708/hourly"
tracking_output_dir: "/nas/home/dkn/Desktop/MoCCA/Derechos/LI_test/output/201708/hourly"

grid_size_km: 11.0
precip_var_name: "precipitation"
liting_index_var_name: "LI"
lat_name: "lat"
lon_name: "lon"
data_source: "IMERG precipitation and ERA5 Lifting Index"

# Detection parametersS
min_size_threshold: 10
heavy_precip_threshold: 8.0
moderate_precip_threshold: 1.0
min_nr_plumes: 1


# Tracking parameters
main_lifetime_thresh: 5
main_area_thresh: 2000
grid_cell_area_km2: 121
nmaxmerge: 5

# Other parameters
use_lifting_index: True
detection: False
use_multiprocessing: True
number_of_cores: 32
